server:
  servlet:
    context-path: /inventory
  port: 8082
spring:
  application:
    name: inventory_service
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  datasource:
    url: jdbc:postgresql://localhost:5432/es_inventory
    username: ihor
    password: qwerty
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: RegistryServiceHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: ihor
    password: root
rabbit:
  orders:
    exchange.name: es.order.events.exchange
    queue.name: es.order.events.queue
    routing.key: order.#
  inventory:
    exchange.name: es.inventory.events.exchange
    success.routing.key: inventory.reserved
    failed.routing.key: inventory.failed
outbox:
  timeout.after.failure.ms: 5000
  events.batch.size: 100
